import type { Citation, CitationFormat } from '@/types';

export function formatCitation(citation: Citation, format: CitationFormat): string {
  const { title, authors, url, publicationDate, publisher, journalName, volume, issue, pages, doi } = citation;
  const authorStr = authors.length > 0 ? authors.join(', ') : 'Unknown Author';
  const year = publicationDate ? new Date(publicationDate).getFullYear() : 'n.d.';

  switch (format) {
    case 'apa': {
      let apa = `${authorStr} (${year}). *${title}*`;
      if (journalName) {
        apa += `. *${journalName}*`;
        if (volume) apa += `, *${volume}*`;
        if (issue) apa += `(${issue})`;
        if (pages) apa += `, ${pages}`;
      } else if (publisher) {
        apa += `. ${publisher}`;
      }
      if (doi) apa += `. https://doi.org/${doi}`;
      else if (url) apa += `. ${url}`;
      return apa + '.';
    }

    case 'mla': {
      let mla = `${authorStr}. "${title}."`;
      if (journalName) {
        mla += ` *${journalName}*`;
        if (volume) mla += `, vol. ${volume}`;
        if (issue) mla += `, no. ${issue}`;
        mla += `, ${year}`;
        if (pages) mla += `, pp. ${pages}`;
      } else if (publisher) {
        mla += ` *${publisher}*, ${year}`;
      }
      if (url) mla += `. ${url}`;
      return mla + '.';
    }

    case 'chicago': {
      let chicago = `${authorStr}. "${title}."`;
      if (journalName) {
        chicago += ` *${journalName}*`;
        if (volume) chicago += ` ${volume}`;
        if (issue) chicago += `, no. ${issue}`;
        chicago += ` (${year})`;
        if (pages) chicago += `: ${pages}`;
      } else if (publisher) {
        chicago += ` ${publisher}, ${year}`;
      }
      if (doi) chicago += `. https://doi.org/${doi}`;
      else if (url) chicago += `. ${url}`;
      return chicago + '.';
    }
  }
}

export function exportCitationsAsText(citations: Citation[], format: CitationFormat): string {
  const formatName = { apa: 'APA', mla: 'MLA', chicago: 'Chicago' }[format];
  const header = `${formatName} CITATIONS\nGenerated by Analyst AI on ${new Date().toLocaleDateString()}\n${'─'.repeat(60)}\n\n`;
  const body = citations
    .map((c, i) => `[${i + 1}] ${formatCitation(c, format)}`)
    .join('\n\n');
  return header + body;
}
