import {
  Document, Packer, Paragraph, TextRun, HeadingLevel,
  AlignmentType, BorderStyle, Table, TableRow, TableCell,
  WidthType, ShadingType,
} from 'docx';

interface ReportSection {
  heading?: string;
  body: string;
}

function parseMarkdownToSections(markdown: string): ReportSection[] {
  const lines = markdown.split('\n');
  const sections: ReportSection[] = [];
  let current: ReportSection = { body: '' };

  for (const line of lines) {
    if (line.startsWith('## ')) {
      if (current.body.trim() || current.heading) sections.push(current);
      current = { heading: line.replace(/^##\s+/, ''), body: '' };
    } else if (line.startsWith('# ')) {
      if (current.body.trim() || current.heading) sections.push(current);
      current = { heading: line.replace(/^#\s+/, ''), body: '' };
    } else {
      current.body += line + '\n';
    }
  }
  if (current.body.trim() || current.heading) sections.push(current);
  return sections;
}

function parseParagraph(text: string): TextRun[] {
  const runs: TextRun[] = [];
  const boldRegex = /\*\*(.+?)\*\*/g;
  let lastIndex = 0;
  let match;

  while ((match = boldRegex.exec(text)) !== null) {
    if (match.index > lastIndex) {
      runs.push(new TextRun({ text: text.slice(lastIndex, match.index) }));
    }
    runs.push(new TextRun({ text: match[1], bold: true }));
    lastIndex = match.index + match[0].length;
  }
  if (lastIndex < text.length) {
    runs.push(new TextRun({ text: text.slice(lastIndex) }));
  }
  return runs.length > 0 ? runs : [new TextRun({ text })];
}

export async function generateDocx(title: string, content: string, author?: string): Promise<Buffer> {
  const sections = parseMarkdownToSections(content);

  const children: Paragraph[] = [
    // Title
    new Paragraph({
      text: title,
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),
    // Metadata
    new Paragraph({
      children: [
        new TextRun({ text: `Generated by Analyst AI`, italics: true, color: '666666' }),
        new TextRun({ text: `  •  `, color: '999999' }),
        new TextRun({ text: new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), italics: true, color: '666666' }),
        ...(author ? [new TextRun({ text: `  •  ${author}`, italics: true, color: '666666' })] : []),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { after: 600 },
    }),
  ];

  // Horizontal rule
  children.push(new Paragraph({
    border: { bottom: { color: 'CCCCCC', style: BorderStyle.SINGLE, size: 1 } },
    spacing: { after: 400 },
    text: '',
  }));

  for (const section of sections) {
    if (section.heading) {
      children.push(new Paragraph({
        text: section.heading,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 200 },
      }));
    }

    const bodyLines = section.body.split('\n');
    for (const line of bodyLines) {
      if (!line.trim()) continue;

      if (line.startsWith('- ') || line.startsWith('• ')) {
        children.push(new Paragraph({
          children: parseParagraph(line.replace(/^[-•]\s+/, '')),
          bullet: { level: 0 },
          spacing: { after: 80 },
        }));
      } else if (/^\d+\.\s/.test(line)) {
        children.push(new Paragraph({
          children: parseParagraph(line.replace(/^\d+\.\s+/, '')),
          numbering: { reference: 'default-numbering', level: 0 },
          spacing: { after: 80 },
        }));
      } else {
        children.push(new Paragraph({
          children: parseParagraph(line),
          spacing: { after: 120 },
        }));
      }
    }
  }

  const doc = new Document({
    sections: [{ children }],
    styles: {
      default: {
        document: {
          run: { font: 'Calibri', size: 24 },
        },
        heading1: {
          run: { font: 'Calibri', size: 32, bold: true, color: '2563EB' },
        },
        title: {
          run: { font: 'Calibri', size: 56, bold: true, color: '1E3A5F' },
        },
      },
    },
  });

  const buffer = await Packer.toBuffer(doc);
  return buffer;
}
